// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UserLoginReply struct {
	Token string `json:"token"`
}
